### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by trlsmax** [fripon/freeture#4] opened 2015-08-29 18:46 UTC
Hi ,
For filter out the plane, what about a speed filter, for example, how many pixel per second, if a object's speed is slower than this, do not record. Just like UFO Capture.

V4L2 support. I want to use a watec 902 with stk1160 capture in linux to capture meteor.

Great software and I will try it.
Thanks.
Max

**Comment by Asubayo** [comment] 2015-09-02 08:08
Hello,

The current detection method doesn't have a speed filter because we use GigE 
cameras with fish eye lens. It is possible to add a speed filter but the deformation caused by the lens
must be corrected. Instead of a speed filter, there is a parameter for the time limit about an event.

About V4L2, it's in progress to fully support usb cameras. For now, it's not yet operational to capture meteors. We work with a DMK Camera (DMx 31AU03.AS). When it will be ready, we will be interested to know if it's correctly work with your camera type.

Thanks for your interest !

**Closed as completed** 2015-09-07 08:32 UTC
